name: kusel
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+46

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dot_navigation_bar: ^1.0.2
  flutter_svg: ^2.0.9
  motion_toast: ^2.12.1
  open_street_map_search_and_pick: ^0.1.1
  geocoding: ^2.1.0
  url_launcher: ^6.2.1
  shimmer: ^3.0.0
  geolocator: ^10.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  connectivity_plus: ^6.1.4
  flutter_compass: ^0.8.1
  flutter_map: ^6.2.1
  permission_handler: ^12.0.0+1
  mobile_scanner: ^7.0.0
  webview_flutter: ^4.13.0
  video_player: ^2.10.0
  device_info_plus: ^10.0.0
  calendar_date_picker2: ^2.0.1
  package_info_plus: ^9.0.0
  core:
    path: core

  domain:
    path: ./domain

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_screenutil: ^5.9.3
  intl: any
  flutter_localizations:
    sdk: flutter
  flutter_typeahead: ^5.2.0
  sliding_up_panel: ^2.0.0+1
  cached_network_image: ^3.4.1
  latlong2: ^0.9.1
  flutter_html: ^3.0.0
  translator: ^1.0.3+1
  upgrader: ^11.4.0
  flame: ^1.30.1

  # database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # For generating type adapters
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/android_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF" # Background color
  image: assets/png/android_icon.png
  android: true
  ios: true


flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/jpg/
    - assets/svg/
    - assets/png/
    - assets/svg/category_icon/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 500

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 500

